printWidth: 120
semi: false
trailingComma: all
arrowParens: always
singleQuote: false
useTabs: false

overrides:
  - files: "lib/vscode/**/*.ts"
    options:
      printWidth: 160

      semi: true
      singleQuote: true
      useTabs: true
